title: MingYu Lu
url: "https://mingyu-lu.github.io/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Linkedin"
   link: "https://www.linkedin.com/in/min-yu-lu-128410108/"
 - name: "Github"
   link: "https://github.com/q8888620002"
 - name: "CV"
   link: "latest_CV.pdf"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=Hp7cv5kAAAAJ&hl=en"
