title: MingYu Lu
url: "https://mingyu-lu.github.io/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://mingyu-lu.github.io/"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Linkinden"
   link: "https://www.linkedin.com/in/min-yu-lu-128410108/"
 - name: "Github"
   link: "https://github.com/q8888620002"
 - name: "CV"
   link: "latest_CV.pdf"
